# PyTorch 기초 텐서 연산 (Tensor Operations)

**학습 목표**

텐서의 개념과 NumPy 배열과의 차이점 이해  
PyTorch 텐서 생성 및 조작 방법 습득  
머신러닝에서 텐서 연산의 실제 활용 사례 학습  
GPU 가속을 위한 텐서 처리 방법 이해 

 ## 1.1 텐서란 무엇인가?  

텐서(Tensor)는 다차원 배열을 일반화한 개념으로, 딥러닝의 모든 데이터 표현의 기본 단위입니다.  

**차원별 텐서의 의미**  

0차원 (스칼라): 단일 숫자 값 (예: 손실값, 정확도)  
1차원 (벡터): 특성 벡터, 가중치 벡터  
2차원 (행렬): 완전연결층의 가중치, 배치 데이터  
3차원: 시계열 데이터 (배치, 시퀀스, 특성)  
4차원: 이미지 데이터 (배치, 채널, 높이, 너비)

In [2]:
# 기본 라이브러리 import
import torch
import numpy as np
import matplotlib.pyplot as plt
import warnings

# 경고 메시지 숨기기
warnings.filterwarnings('ignore')

# 한글 폰트 설정 (Windows 환경)
try:
    plt.rcParams['font.family'] = 'Malgun Gothic'
except:
    plt.rcParams['font.family'] = 'DejaVu Sans'
    print("한글 폰트를 찾을 수 없어 기본 폰트를 사용합니다.")

plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['figure.figsize'] = (8, 6)

# PyTorch 버전 및 환경 확인
print(f"PyTorch 버전: {torch.__version__}")
print(f"CUDA 사용 가능: {torch.cuda.is_available()}")

# 기본 장치 설정 (CPU 사용)
device = torch.device('cpu')
print(f"사용 장치: {device}")
print("모든 준비 완료! 텐서 연산 학습을 시작합니다!")

PyTorch 버전: 2.5.1
CUDA 사용 가능: False
사용 장치: cpu
모든 준비 완료! 텐서 연산 학습을 시작합니다!


##  1.2 텐서 생성 방법들

1. 직접 데이터로부터 생성  
2. NumPy 배열로부터 생성  
3. 0으로 채워진 텐서 (모델 가중치 초기화에 주로 사용)  
4. 1로 채워진 텐서 (bias 초기화에 주로 사용)  
5. 단위 행렬 (항등 변환에 사용)  
6. 랜덤 텐서 생성 - 딥러닝에서 가장 중요!

In [4]:
# 1. 직접 데이터로부터 생성
data = [[1, 2], [3, 4]]
tensor_from_data = torch.tensor(data)
print("데이터로부터 생성:")
print(tensor_from_data)
print(f"Shape: {tensor_from_data.shape}")
print(f"데이터 타입: {tensor_from_data.dtype}")
print()

데이터로부터 생성:
tensor([[1, 2],
        [3, 4]])
Shape: torch.Size([2, 2])
데이터 타입: torch.int64



In [5]:
# 2. NumPy 배열로부터 생성
np_array = np.array([[1, 2, 3], [4, 5, 6]])
tensor_from_numpy = torch.from_numpy(np_array)

print("NumPy 배열:")
print(np_array)
print("\nNumPy에서 변환된 텐서:")
print(tensor_from_numpy)

# 텐서를 다시 NumPy로 변환
back_to_numpy = tensor_from_numpy.numpy()
print("\n텐서에서 NumPy로 재변환:")
print(back_to_numpy)
print(f"원본과 동일한가? {np.array_equal(np_array, back_to_numpy)}")

NumPy 배열:
[[1 2 3]
 [4 5 6]]

NumPy에서 변환된 텐서:
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

텐서에서 NumPy로 재변환:
[[1 2 3]
 [4 5 6]]
원본과 동일한가? True


In [6]:
# 3. 0으로 채워진 텐서 (모델 가중치 초기화에 주로 사용)
zeros_tensor = torch.zeros(3, 4)
print("0으로 채워진 텐서:")
print(zeros_tensor)

# 4. 1로 채워진 텐서 (bias 초기화에 주로 사용)
ones_tensor = torch.ones(2, 3)
print("\n1로 채워진 텐서:")
print(ones_tensor)

# 5. 단위 행렬 (항등 변환에 사용)
identity_tensor = torch.eye(3)
print("\n단위 행렬:")
print(identity_tensor)

0으로 채워진 텐서:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

1로 채워진 텐서:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

단위 행렬:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [7]:
# 6. 랜덤 텐서 생성 - 딥러닝에서 가장 중요!
torch.manual_seed(42)  # 재현 가능한 결과를 위한 시드 설정

# 0과 1 사이의 균등 분포
uniform_tensor = torch.rand(2, 3)
print("균등 분포 랜덤 텐서 (0~1):")
print(uniform_tensor)

# 표준 정규 분포 (평균 0, 표준편차 1)
normal_tensor = torch.randn(2, 3)
print("\n표준 정규 분포 랜덤 텐서:")
print(normal_tensor)

# 정수 범위 랜덤 텐서
randint_tensor = torch.randint(0, 10, (2, 3))
print("\n정수 랜덤 텐서 (0~9):")
print(randint_tensor)

균등 분포 랜덤 텐서 (0~1):
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

표준 정규 분포 랜덤 텐서:
tensor([[ 1.1561,  0.3965, -2.4661],
        [ 0.3623,  0.3765, -0.1808]])

정수 랜덤 텐서 (0~9):
tensor([[7, 6, 9],
        [6, 3, 1]])
